This folder structure contains the Dockerfiles for building RabbitMQ clusters with high availability and haproxy instance running on top of them - the number of nodes are completely customizable using https://docs.docker.com/compose/[docker-compose] docker-compose.yml file.


Structure:
==========
There are 3 folders.

1. base - this is the base Dockerfile which builds on a CentOS image and installs the RabbitMQ binaries on the image
2. server - This builds on the base image and has the startup script for bring up a RabbitMQ server
3. haproxy - This folder contains the Dockerfile that creats the haproxy image configured for master-slave setup
4. cluster - This contains a https://docs.docker.com/compose/[docker-compose] definition file(docker-compose.yml) for brining up the rabbitmq cluster. Use `docker-compose up -d` to bring up the cluster.

High availability achieved by using the configuration below in startrabbit.sh.This configuration will be mirroring
all the queues to the all nodes in the cluster.You can read more on highly available rabbitmq clustering  https://www.rabbitmq.com/ha.html[here].

[source]
----
rabbitmqctl set_policy ha-all "." '{"ha-mode":"all","ha-sync-mode":"automatic"}'
----


Running the Cluster:
===============================
Once the images are built, boot up the cluster using the docker-compose.yml configuration provided in cluster folder:

[source]
----
docker-compose up -d
----

By default 2 nodes and 1 haproxy container are started up this way:
Note: You can remove port mappings for rabbit nodes since they will be accessed
by haproxy instance.I opened them up to access from outside world to rabbit nodes.

[source]
----
rabbit1:
  image: bijukunjummen/rabbitmq-server
  hostname: rabbit1
  ports:
    - "5672:5672"
    - "15672:15672"

rabbit2:
  image: bijukunjummen/rabbitmq-server
  hostname: rabbit2
  links:
    - rabbit1
  environment:
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit1
   - RAM_NODE=true
  ports:
      - "5673:5672"
      - "15673:15672"

rabbit3:
  image: bijukunjummen/rabbitmq-server
  hostname: rabbit3
  links:
    - rabbit1
    - rabbit2
  environment:
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit1
  ports:
        - "5674:5672"
----

if needed, additional nodes can be added to this file. If the entire cluster comes up, the management console can be accessed at http://<dockerip>:15670
Connections to the rabbitmq server should be made through haproxy instace, that is http://<dockerip>:5670
You can view stats page of haproxy using: http://<dockerip>:8100/stats

and connection host should look like this: `dockerip:5672,dockerip:5673`

