rabbit1:
  image: davidlu1001/rabbitmq-ha-cluster
  hostname: rabbit1
  ports:
    - "5672:5672"
    - "15672:15672"

rabbit2:
  image: davidlu1001/rabbitmq-ha-cluster
  hostname: rabbit2
  links:
    - rabbit1
  environment:
   - CLUSTERED=true
   - CLUSTER_WITH=rabbit1
  ports:
        - "5673:5672"
        - "15673:15672"

haproxy:
  image: davidlu1001/rabbitmq-ha-haproxy
  hostname: haproxy
  links:
    - rabbit1
    - rabbit2
  ports:
    - "8100:8100"
    - "5670:5670"
    - "15670:15670"
